### ISSUE TITLE
bug: query validation

### ISSUE THREAD

**Issue by ChrisK1994** [ngduc/node-rem#167]
If the query is: 
`http://localhost:3009/v1/users?role=admin&limit=5&offset=0&sort=email:desc,createdAt`
shouldn't validation be:
```
listUsers: {
    query: Joi.object({
      page: Joi.number().min(1),
      perPage: Joi.number().min(1).max(100),
      limit: Joi.number().min(1),
      offset: Joi.number().min(1),
      role: Joi.string().valid(...User.roles),
      sort: Joi.string(),
    })
  }
```
instead of:

```
listUsers: {
    query: Joi.object({
      page: Joi.number().min(1),
      perPage: Joi.number().min(1).max(100),
      name: Joi.string(),
      email: Joi.string(),
      role: Joi.string().valid(...User.roles)
    })
  }
```
  
I might be wrong but the second one doesn't work for me, it gives - validation error

**Comment by ngduc** [comment]
I didn't update Joi validation for a while. I will check that api call shortly and update here. Thanks.

**Comment by ngduc** [comment]
Note that the endpoint above "/users" requires admin auth token (logged in as an admin) to be able to list users.
With the admin auth token, it works for me:
http://localhost:3009/v1/users?role=admin&limit=5&offset=0&sort=email:desc,createdAt
```
{
    "data": [
        {
            "id": "6035fac2e9f15b66900b5e87",
            "name": "Bran Stark",
            "email": "branstark@gmail.com",
            "role": "admin",
            "createdAt": "2021-02-24T07:05:38.418Z"
        },
        {
            "id": "60360956d3e4555a408e10b8",
            "email": "admin2@example.com",
            "role": "admin",
            "createdAt": "2021-02-24T08:07:50.028Z"
        },
        {
            "id": "60360955d3e4555a408e10a3",
            "email": "admin1@example.com",
            "role": "admin",
            "createdAt": "2021-02-24T08:07:49.565Z"
        }
    ],
    "meta": {
        "limit": 5,
        "offset": 0,
        "sort": {
            "email": -1,
            "createdAt": 1
        },
        "totalCount": 3,
        "count": 3,
        "timer": 54.79,
        "timerAvg": 38.14
    }
}
```

**Comment by ChrisK1994** [comment]
it works because it is not being validated at all, so your query is passing but validation doesn't work

**Comment by ngduc** [comment]
updated code to use:
```
listUsers: {
    query: {
      limit: Joi.number().min(1).max(9999),
      offset: Joi.number().min(0),
      page: Joi.number().min(0),
      perPage: Joi.number().min(1),
      sort: Joi.string(),
      name: Joi.string(),
      email: Joi.string(),
      role: Joi.string().valid(User.roles)
    }
  }
```
It does validation. I used VSCode Rest Client to run API example call in "rest-client-examples.rest" file.
"/v1/users?limit=5&offset=-1&sort=email:desc,createdAt"

```
"messages": [
  "\"offset\" must be larger than or equal to 0"
]
```

**Comment by ChrisK1994** [comment]
try to validate 'name' or 'role'

**Comment by ngduc** [comment]
Thanks for replying @ChrisK1994 
I've just tried with name and role, it seems to work for me:

/v1/users?limit=5&offset=0&sort=email:desc,createdAt&role=bogus

getting an error message: "\"role\" must be one of [user, admin]"
