### ISSUE TITLE
Error on dev

### ISSUE THREAD

**Issue by samburgers** [ngduc/node-rem#27]
Great looking project! Seem to get an error on dev however

`yarn docker:dev`

output...
```
[5/5] Building fresh packages...
$ cd ./node_modules && node ../package_symlinks.js && cd ..
module.js:550
    throw err;
    ^

Error: Cannot find module '/app/package_symlinks.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
error Command failed with exit code 1.
```

**Comment by ducwings** [comment]
Thanks. I'll check tonight. That script just creates symlinks from src/api and src/config to node_modules for easy imports.

**Comment by ngduc** [comment]
Hi @samburgers Do you still experience that error?

**Comment by samburgers** [comment]
yep i get the error still when running with docker... `yarn docker:dev`

**Comment by samburgers** [comment]
Same platform as above, MacOS Mojave, Node 8+, Yarn latest
