### ISSUE TITLE
many path Error: Cannot find module '../xxx'

### ISSUE THREAD

**Issue by JipingWang** [ngduc/node-rem#51]
**many modules not found**

**Error: Cannot find module 'xxx'**
- Error: Cannot find module '../models/refreshToken.model'
- ... many more like this
  
**Environment Details**
  * OS: Windows 10
  * Node.js version: v8.12.0
  * npm version: 6.4.1

**Long Description**
- I manually updated some, but it seems i need to configure something?

**Comment by ngduc** [comment]
@JipingWang I haven't tested it on Windows 10 yet but I guess this script `package_symlinks.js` couldn't create symlinks 'api', 'config' in node_modules. If you could create a PR to fix that script for Win10, that will be great!

**Comment by ngduc** [comment]
@JipingWang I've just got a chance to run node-rem on Windows 10 Powershell. I fixed "yarn dev" so it should work now :]

**Comment by Jiping-hi** [comment]
@ngduc , thanks for the update. 
 

> 'ts-node' =>  ts-node

That's what I did as a fix, just didn't know if it is the right way.
